replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: grpc
      protocol: TCP

containerPorts:
  - name: http
    port: 8000
    protocol: TCP
  - name: grpc
    port: 9000
    protocol: TCP


probes:
  liveness:
    enabled: false
    path: /
    port: http
  readiness:
    enabled: false
    path: /
    port: http

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumeMounts:
  - name: ticketing-config
    mountPath: /ticketing/conf
volumes:
  - name: ticketing-config
    secret:
      secretName: itsm
      defaultMode: 420
      items:
        - key: ticketing.yaml
          path: config.yaml

nodeSelector: {}
tolerations: []
affinity: {}

